export const dataMiniature = [
    {"image": "https://i.imgur.com/u1WVOVB.jpg", "titre": "Bande Original de Risifight", "ID": "BOrisifight"},
    {"image": "https://i.imgur.com/u1WVOVB.jpg", "titre": "Musique pour Risimon", "ID": "BOrisimon"},
    {"image": "https://i.imgur.com/u1WVOVB.jpg", "titre": "Musique anti Trapvador", "ID": "piano"},
    {"image": "https://i.imgur.com/1Hp3qoG.jpg", "titre": "Film Onchois 2D", "ID": "filmOnchois2D"},
    {"image": "https://i.imgur.com/1Hp3qoG.jpg", "titre": "Film Onchois 3D", "ID": "filmOnchois3D"},
    {"image": "https://i.imgur.com/1Hp3qoG.jpg", "titre": "Cinématique Risifight", "ID": "cinematique"},
    {"image": "https://i.imgur.com/1Hp3qoG.jpg", "titre": "Le fou sous le lit dream", "ID": "lit"},
    {"image": "https://i.imgur.com/ceoqTBO.jpg", "titre": "Fou du Village Dream Simulator 2D", "ID": "FDV2D"},
    {"image": "https://i.imgur.com/ceoqTBO.jpg", "titre": "Fou du Village Dream Simulator 3D", "ID": "FDV3D"},
    {"image": "https://i.imgur.com/ceoqTBO.jpg", "titre": "Le Jeu du taréent", "ID": "tarot"},
    {"image": "https://i.imgur.com/ceoqTBO.jpg", "titre": "Il faut enculer le gang de Trapvador", "ID": "trap"},
    {"image": "", "titre": "", "ID": ""},
]

export const dataComplete = [
    {
        "ID": "BOrisifight", 
        "section": "true",
        "description": "Risifight est un MMORPG développé par le khey Kirabium. Bitler est le compositeur du jeu et a composé 1h de musique orchestrale pour le jeu. A l'heure ou j'écris ce texte, Bitler n'a plus de nouvelle de Kirabium et ne compose plus.",
        "lienExterne": ["https://jvflux.fr/Risifight"],
        "titre": "Bande Original de Risifight", 
        "lienInfo": {"lien": "UpOWZosz5u8?si=eAAygwTSrht75whZ", "type": "youtube"},
        "sommaire": ["0:05 Ambiance biome plage n°1", 
                        "0:30 Idée n°2", 
                        "3:43 Ambiance biome grotte",
                        "5:03 Ambiance biome montagne",
                        "7:01 Ambiance biome plage n°2",
                        "9:27 Combat biome Pokémon",
                        "11:47 Idée n°3",
                        "14:19 Idée n°4",
                        "16:45 Combat biome plage",
                        "17:13 Combat boss Lidl",
                        "19:18 Idée n°1",
                        "20:20 Mort boss Lidl",
                        "21:25 Combat tour de combat",
                        "24:47 Combat biome neige",
                        "28:32 Combat biome montagne",
                        "31:38 Ambiance commissariat n°2",
                        "34:11 Ambiance biome neige",
                        "36:15 (Usul) Ambiance commissariat n°1",
                        "37:01 Ambiance tour de combat n°3",
                        "37:31 Ambiance tour de combat n°2",
                        "38:34 Ambiance Lidl",
                        "40:01 Ambiance biome forêt",
                        "38:34 Ambiance Lidl",
                        "40:01 Ambiance biome forêt",
                        "43:08 Ambiance tour de combat n°1",
                        "43:42 Combat contre Gilbert",
                        "45:51 Combat biome fou du village",
                        "47:23 Ambiance biome fou du village",
                        "49:30 Arène Combat",
                        "51:22 Ambiance biome Pokémon",
                    ]
    },
    {
        "ID": "BOrisimon", 
        "section": "true",
        "description": "Risimon est un FanGame Pokémon développé par les kheys de JeuxVidéo.com. Bitler a fait parti de l'équipe des compositeurs du jeu avant de quitter le projet. L'équipe de Risimon lui a demandé de revenir par le biais d'un topic. Bitler est revenu collaborer avant de repartir définitivement.",
        "lienExterne": ["https://jvflux.fr/Risimon_(jeu_vid%C3%A9o)", 
                        "https://jvarchive.com/forums/42-51-70420450-1-0-1-0-risimon-j-invoque-le-khey-bitler-en-force",
                        "https://voca.ro/1dss75iTFGFk"],
        "titre": "Musiques pour Risimon", 
        "lienInfo": {"lien": "Qzl2DTYaZ_g?si=ikN_GTnfxMCrTxsq", "type": "youtube"},
        "sommaire": ["0:04 Idée n°3", 
                    "1:34 Idée n°2", 
                    "2:40 Idée n°1",
                    "4:26 Montagne",
                    "6:34: Surf",
                    "8:16 Caverne",
                    "9:56 Chad",
                    "11:43 Village de Kondé sur Noireau",
                    "14:02 Team GOLEM",
                    "14:29 Zic jeu",
                    ]
    },
    {
        "ID": "filmOnchois2D", 
        "section": "false",
        "description": "Le film onchois est un film hommage a onche et l'épisode 5 de la guerre Bitler vs Trapvador. Le khey Limedea s'occupait du doublage et du scénario, Bitler s'occupait des dessin du montage et de la musique. Dans une démarche de faire un projet toujouts plus gros, la version 2D du film a été abandonnée pour faire une version 3D.",
        "lienExterne": ["https://onche.org/topic/231371/officiel-film-onchois-le-projet-a-serieusement-commence"],
        "titre": "Film Onchois 2D", 
        "lienInfo": {"lien": "8cfjDfNyYuQ?si=1mAPX5vqshV74FdQ", "type": "youtube"},
        "sommaire": ["Rien"]
    },
    {
        "ID": "filmOnchois3D", 
        "section": "false",
        "description": "Le film onchois est un film hommage a onche et l'épisode 5 de la guerre Bitler vs Trapvador. Le khey Limedea s'occupait du doublage et du scénario, Bitler s'occupait des dessin de la 3D du montage et de la musique. Suite a des problèmes d'argent dans la vie de Bitler, le film a du être annulé.",
        "lienExterne": ["https://onche.org/topic/351816/le-film-onchois-est-annule-explication-je-rends-public-tout-les-travaux"],
        "titre": "Film Onchois 3D", 
        "lienInfo": {"lien": "aGHTUOcAlyM?si=jKzZVDtIBorL3o5a", "type": "youtube"},
        "sommaire": ["Rien"]
    },
    {
        "ID": "FDV2D", 
        "section": "false",
        "description": "Bitler aimait beaucoup le délire du khey Revenant sur Le Fou du VIllage Dream. Il a décidé d'en faire un jeu vidéo en HTML CSS JavaScript. Par manque de temps il n'a pas pu le terminé.",
        "lienExterne": ["https://onche.org/topic/234403/jeu-video-fou-du-village-dream-simulator-2d",
                        "https://mega.nz/folder/FX9hnDLT#5LTLHup0c0cK3ycKFupKhA",
                        "https://fdv-simulator.vercel.app/"],
        "titre": "Fou du VIllage Dream Simulator 2D", 
        "lienInfo": {"lien": "WMaL1UI2aM8?si=L-6g_4GkIpgXr2zl", "type": "youtube"},
        "sommaire": ["Rien"]
    },
    {
        "ID": "FDV3D", 
        "section": "false",
        "description": "Bitler aimait beaucoup le délire du khey Revenant sur Le Fou du VIllage Dream. Il a décidé d'en faire un jeu vidéo en 3D. Par manque de connaissance en 3D il ne l'a pas terminé.",
        "lienExterne": ["https://onche.org/topic/208305/fou-du-village-dream-simulator-3d"],
        "titre": "Fou du VIllage Dream Simulator 3D", 
        "lienInfo": {"lien": "a6wWlQUspqE?si=IRiSSCzY1O8C18Wb", "type": "youtube"},
        "sommaire": ["Rien"]
    },
    {
        "ID": "tarot", 
        "section": "false",
        "description": "Le khey onchois Anakintunwookie a proposé a Bitler de faire un version parodique du tarot divinatoire. Bitler a accepté de faire un site pour le jeu. Mais aucun graphiste ne s'est manifesté pour dessiné les cartes. Le projet a fini par tombé à l'eau.",
        "lienExterne": ["https://onche.org/topic/141334/creer-un-jeu-du-tareent-jeu-du-tarot-inspire-des-delires-de-l-elite"],
        "titre": "Le Jeu du taréent", 
        "lienInfo": {"lien": "hEEJmfm83Tk?si=ax2U4GBMlaR7NA0t", "type": "youtube"},
        "sommaire": ["Rien"]
    },
    {
        "ID": "trap", 
        "section": "false",
        "description": "L'épisode 3 de la guerre de Bitler vs Trapvador. Bitler a fait un jeu vidéo sous forme de site internet avec des cinématiques.",
        "lienExterne": ["https://onche.org/topic/201953/alerte-rouge-je-brise-definitivement-trapvador", "https://trapvador-gang-le-jeu.vercel.app/"],
        "titre": "Il faut enculer le gang de Trapvador", 
        "lienInfo": {"lien": "2EKGqQ1IuCs?si=9GTWQH2uPzbNvh33", "type": "youtube"},
        "sommaire": ["Rien"],
    },
    {
        "ID": "piano", 
        "section": "false",
        "description": "L'épisode 1 de la guerre de Bitler vs Trapvador. Bitler exprime sa vaillance contre trapvador en composant une musique au piano.",
        "titre": "Musique anti Trapvador", 
        "lienInfo": {"lien": "wrnX9bjQ_bY?si=G46XfhYsl2vB__iJ", "type": "youtube"},
        "sommaire": ["Rien"],
    },
    {
        "ID": "cinematique", 
        "section": "false",
        "description": "Les cinématiques faites par Bitler pour le MMORPG Risifight",
        "titre": "Cinématiques du jeu Risifight", 
        "lienInfo": {"lien": "9O01CA36Uho?si=7m7KL3ZD6GIUXg0t", "type": "youtube"},
        "sommaire": ["Rien"],
    },
    {
        "ID": "lit", 
        "section": "false",
        "description": "Une idée originale de Bitler",
        "titre": "Le Fou sous le lit dream", 
        "lienInfo": {"lien": "818tILCWuy4?si=5S7Mv7g2dPylZMqd", "type": "youtube"},
        "sommaire": ["Rien"],
    },
]